version: '2'
services:
  web:
    build: .
    image: meow
    restart: always
    command: honcho start -f Procfile
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - public
      - meow_svc
    
  db:
    image: postgres:latest
    volumes: 
      - /opt/meow/db:/var/lib/postgresql/
    restart: always
    networks:
      - meow_svc

  redis:
    restart: always
    image: redis:alpine
    networks:
      - meow_svc

networks:
  public:
    external:
      name: public
  meow_svc:
    driver: bridge
